name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install dependencies
        run: pip install black==25.* isort==6.* flake8==7.*
      # Different line limits: Black/isort (120), Flake8 (150). 
      # Flake8 allows longer lines for better long string readability. Black doesn't enforce string length.
      - name: Run black
        run: black --line-length=120 --check --diff .
      - name: Run flake8
        run: flake8 --max-line-length=150
      - name: Run isort
        run: isort --check --diff --profile black --line-length=120 .
      - name: Run PowerShell linter
        run: scripts/lint.ps1


