VM_NAME: FLARE-VM.testing
EXPORTED_VM_NAME: FLARE-VM.Win10
SNAPSHOTS:
- extension: ".EDU"
  description: "Windows 10 VM with FLARE-VM default configuration + FLARE-EDU materials"
  cmd: |
    $desktop = "C:\Users\flare\Desktop";
    Set-Location $desktop;

    # Unzip EDU labs
    VM-Unzip-Recursively;

    # Install Office 2016. the installation takes 30 minutes
    $path = "$desktop\en_office_professional_plus_2016_x86_x64_dvd_6962141.iso";
    $drive = (Mount-DiskImage -ImagePath $path | Get-Volume).DriveLetter;
    Set-Location "$drive`:\";
    .\setup.exe;
    Start-Sleep 1800;
    Dismount-DiskImage -ImagePath $path;

    # Ensure files are written to persistent storage as the script shut down the VM abruptly
    # sync is installed by sysinternals
    sync;
  legal_notice: "legal_notice_edu.txt"
  protected_folders: "'ATMA', 'MACC', 'MAF', 'MDA'"
  protected_files: "'Labs.zip', 'MICROSOFT Windows 10 License Terms.txt', 'MICROSOFT Office 2016 License Terms.txt'"
